[project]
name = "ai-engineering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.1.0",
    "openai>=2.16.0",
    "python-dotenv>=1.2.1",
    "yfinance>=1.1.0",
]
